### ISSUE TITLE
appointment form: add link to services info page

### ISSUE THREAD

**Issue by amisinghal** [bawejahritik/AutoServ#96]
what if the user has no idea about the services while filling up the appointment form, so there is a need of adding the link to services information page near the services options.

**Comment by raghavsoni114** [comment]
Instead of having a different page for service info shouldn't we move service details to schedule page and have a smaller application form?

![image](https://user-images.githubusercontent.com/42437530/155651520-86749177-fd0f-4f7a-b1a7-3a7dc8e8564e.png)

This would reduce clicks to get information and would become more user friendly

**Comment by raghavsoni114** [comment]
We'll create a separate issue and look into this in further sprints

**Comment by raghavsoni114** [comment]
For now I'll route "need help" to service page
